/**
 * Engineering Cockpit Endpoint Registry
 * Central registry for all industrial-grade API paths.
 */

export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_ACCOUNT: "/auth/verify-account",
    CHANGE_PASSWORD: "/auth/change-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    RESEND_OTP: "/auth/resend-otp",
    VERIFY_RESET_PASSWORD_OTP: "/auth/verify-reset-password-otp",
  },
  NOTIFICATIONS: {
    GET_ALL: "/notification/",
    READ_ALL: "/notification/read-all",
    UNREAD: "/notification/unread",
    MARK_READ: (id: string) => `/notification/${id}/read`,
  },
  PROFILE: "/profile/",
  PROFILE_UPDATE: "/profile/update",
  TIER2_UPGRADE: "/tiers/upgrade/tier2",
  TIER3_UPGRADE: "/tiers/upgrade/tier3",
  TRANSACTIONS: "/transactions",
  UPLOAD_AVATAR: "/uploads/user",
  WALLET_BALANCE: "/wallet/",
  SWAPS: {
    SWAPS: "/swaps",
    SWAP_RATES: "/swaps/rates",
  },
  FIAT_ACCOUNTS: "/fiat-accounts",
  TRANSFERS: {
    INTERNAL: "/transfers",
    RESOLVE_ACCOUNT: "/transfers/resolve-account",
    SEARCH_PAYID: "/transfers/resolve-payid",
    ACTION_REQUEST: "/transfers/action-request",
    CREATE_REQUEST: "/transfers/create-request",
    REQUESTS: "/transfers/requests",
  },
  WITHDRAWAL: {
    INITIATE: "/withdrawal/initiate",
    LIST_BANKS: "/withdrawal/list-banks",
    RESOLVE_ACCOUNT: "/withdrawal/resolve-account",
  },
  ACCOUNT: {
    SET_PIN: "/account/set-pin",
    VERIFY_PIN_RESET: "/account/verify-pin-reset",
    RESEND_PIN_OTP: "/account/resend-pin-otp",
    FORGOT_PIN: "/account/forgot-pin",
    ENABLE_BIOMETRIC: "/account/enable-biometric",
    DISABLE_BIOMETRIC: "/account/disable-biometric",
    CHANGE_PIN: "/account/change-pin",
  },
  VAS: {
    AIRTIME_PURCHASE: "/vas/airtime-purchase",
    CABLE_PURCHASE: "/vas/cable-subscription-purchase",
    DATA_PURCHASE: "/vas/data-purchase",
    ELECTRICITY_PURCHASE: "/vas/electricity-purchase",
    VERIFY_CABLE: "/vas/verify-cable-number",
    VERIFY_DISCO: "/vas/verify-disco-number",
    CABLE_VARIATIONS: "/vas/cable-variations",
    DATA_VARIATIONS: "/vas/data-variations",
  },
  SAVINGS: {
    GOALS: "/savings/goals",
    CREATE_GOAL: "/savings/goal",
    SAYT: "/savings/sayt",
    BREAK: (id: string) => `/savings/${id}/break`,
    FUND: (id: string) => `/savings/${id}/fund`,
    WITHDRAW: (id: string) => `/savings/${id}/withdraw`,
    HISTORY: (id: string) => `/savings/${id}/history`,
  },
  BENEFICIARIES: {
    GET_ALL: "/beneficiaries",
    CREATE: "/beneficiaries",
    DELETE: (id: string) => `/beneficiaries/${id}`,
  },
  DEVICES: {
    GET_ALL: "/devices/",
    VERIFY_NEW_DEVICE: "/devices/verify",
    RESEND_OTP: "/devices/resend-otp",
    REMOVE: (id: string) => `/devices/${id}`,
    UPDATE_TOKEN: (id: string) => `/devices/${id}/token`,
  },
  REWARDS: {
    GET_ALL: "/rewards/",
    BALANCE: "/csb/",
    REDEEM: "/csb/redeem",
  },
};
